/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ru.sfedu.bideet.Services;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.*;
import ru.sfedu.bideet.ConfigUtils;
import ru.sfedu.bideet.Constants;
import ru.sfedu.bideet.Entities.*;
import ru.sfedu.bideet.Repository.*;
import ru.sfedu.bideet.RoundJTextField;
import ru.sfedu.bideet.RoundedBorder;

/**
 *
 * @author Osebi
 */
public class OngoingBidPane1 extends javax.swing.JFrame {

    /**
     * Creates new form OngoingBidPane1
     */
    
    JPanel panel = new JPanel();
    private JLabel title;
    private JLabel lprice;
    public JTextField price;
    private JButton bid;
    private Font labelFont = new Font("Serif", Font.BOLD, 15);
    private Font textFont = new Font("Serif", Font.PLAIN, 14);
    private Color labelColor = new Color(255,255,255);
    private Color textColor = new Color(35,35,35);
    private Color textArea = new Color(255,255,255);
    
    public OngoingBidPane1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setFont(new java.awt.Font("Source Serif Pro", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setText("See Today's Auctions");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setText("View Bids");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown

    }//GEN-LAST:event_jTable1ComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
    }//GEN-LAST:event_jTable1MouseClicked

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //For csv file
        //String path = "src/main/resources/CSVFILES/Product.csv";
        //For txt file
        String path = "src/main/resources/TXTFILES/Product.txt";
        File file = new File(path);

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columns = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setColumnIdentifiers(columns);

            Object[] tableLines = br.lines().toArray();

            for (int i = 0; i < (tableLines.length); i++) {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(",");
                //String[] row = tableLines[i].toString().split(",");
                
                //for txt
                model.addRow(dataRow);
                
                //for csv
                //if( i%2==0){
                 //   model.addRow(dataRow);
                //}


            }
            jTable1.getColumnModel();
            jTable1.setDefaultEditor(Object.class, null);
            jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                int index = jTable1.getSelectedRow();
                
                TableModel model = jTable1.getModel();
                //for csv
                //String line1 = model.getValueAt(index, 1).toString();
                //String line2 = model.getValueAt(index, 2).toString();
                //String line3 = model.getValueAt(index, 5).toString();
                
                //for txt
                String line1 = model.getValueAt(index, 0).toString();
                String line2 = model.getValueAt(index, 1).toString();
                String line3 = model.getValueAt(index, 4).toString();
                
                System.out.println(line1 + ", " + line2 + ", " + line3);
                //Bid bid1 = new Bid();
                String bid = JOptionPane.showInputDialog(null, "Place Bid");
                System.out.println("OGBP1: " + bid);

                float bidPrice = Float.parseFloat(bid);
                float winBid = 0;
                if (bidPrice > winBid){
                    winBid = bidPrice;
                }
                
                AuctionProduct aucprod = new AuctionProduct();
                aucprod.setProductId(Integer.valueOf(line1));
                aucprod.setProductName(line2);
                aucprod.setStartPrice(line3);
                aucprod.setDate(new Date());
                aucprod.setCurrentBid(bidPrice);
                
                
                try {
                    DataProviderCSV csv = new DataProviderCSV();
                    csv.saveRecordAuctionProduct(aucprod);
                    DataProviderTXT txt = new DataProviderTXT();
                    txt.saveRecordAuctionProduct(aucprod);
                } catch (Exception ex) {
                    Logger.getLogger(OngoingBidPane1.class.getName()).log(Level.SEVERE, null, ex);
                }
                    
                
                
//                int col = jTable1.columnAtPoint(evt.getPoint());
//                if (col == 3) {
//                   // TODO: handle cell click
//                    Bid bid = new Bid();
//                    //bid.show();
//                    //dispose();
//                }
            }
            });

        } catch (IOException ex) {
            Logger.getLogger(OngoingBidPane1.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            ViewAuctions vAuc = new ViewAuctions();
        } catch (IOException ex) {
            Logger.getLogger(OngoingBidPane1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OngoingBidPane1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OngoingBidPane1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OngoingBidPane1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OngoingBidPane1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new OngoingBidPane1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
